- cnt_img_path: data/content/A helmet displayed on a wooden stand.png
  cnt_prompt: A helmet displayed on a wooden stand
  sty_img_path: data/style/Graffiti___07.jpg
  sty_prompt: ''
  edit_prompt: ''
- cnt_img_path: data/content/A honey jar and an orange.png
  cnt_prompt: A honey jar and an orange
  sty_img_path: data/style/Neofigurative___04.jpg
  sty_prompt: ''
  edit_prompt: ''
- cnt_img_path: data/content/An ancient Chinese bronze ding vessel with intricate patterns and motifs.png
  cnt_prompt: An ancient Chinese bronze ding vessel with intricate patterns and motifs
  sty_img_path: data/style/Abstract___04.jpg
  sty_prompt: ''
  edit_prompt: ''
- cnt_img_path: data/content/Lighthouse on the coast.png
  cnt_prompt: Lighthouse on the coast
  sty_img_path: data/style/Cyberpunk___02.jpg
  sty_prompt: ''
  edit_prompt: ''
- cnt_img_path: data/content/objects including a wine bottle, a wine glass, a bowl, a decorative bottle, and a sphere.png
  cnt_prompt: objects including a wine bottle, a wine glass, a bowl, a decorative bottle, and a sphere
  sty_img_path: data/style/Realism___04.jpg
  sty_prompt: ''
  edit_prompt: ''
- cnt_img_path: data/content/Small house on the road.png
  cnt_prompt: Small house on the road
  sty_img_path: data/style/Lineart___07.jpg
  sty_prompt: ''
  edit_prompt: ''