- cnt_img_path: /home/stud_lab_vk_01/Guide-and-Rescale/data/content/detailed_street.jpg
  cnt_prompt: An image
  edit_prompt: ''
  sty_img_path: /home/stud_lab_vk_01/Guide-and-Rescale/data/style/moonk.jpg
  sty_prompt: ''
- cnt_img_path: /home/stud_lab_vk_01/Guide-and-Rescale/data/content/face2.jpg
  cnt_prompt: An image
  sty_img_path: /home/stud_lab_vk_01/Guide-and-Rescale/data/style/lines.jpg
  sty_prompt: ''
  edit_prompt: ''