- cnt_img_path: data/content/face2.jpg
  cnt_prompt: A photo
  sty_img_path: data/style/moonk.jpg
  sty_prompt: Moonk's "The scream" painting
  edit_prompt: Moonk's "The scream" painting
- cnt_img_path: data/content/face2.jpg
  cnt_prompt: A photo
  sty_img_path: data/style/picasso.jpg
  sty_prompt: Picasso's painting
  edit_prompt: Picasso's painting
- cnt_img_path: data/content/square.png
  cnt_prompt: Picture of a primitive square shape
  sty_img_path: data/style/moonk.jpg
  sty_prompt: Moonk's "The scream" painting
  edit_prompt: Moonk's "The scream" painting
- cnt_img_path: data/content/square.png
  cnt_prompt: Picture of a primitive square shape
  sty_img_path: data/style/picasso.jpg
  sty_prompt: Picasso's painting
  edit_prompt: Picasso's painting