run_name: ???
hydra:
  mode: ${hydra.mode}
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}___${run_name}
  sweep:
    dir: ./hydra_multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}___${run_name}
    subdir: ${hydra.job.num}

device: cuda:1
defaults:
  - guidance_cfg: exp24_attnmap_v_style
  - samples: demo_samples

scheduler_name: ddim_50_eps
model_name: stable-diffusion-v1-4

exp_configs:
  qkv_guider_start: 0
  qkv_guider_end: 50
  qkv_guider_scale: 1.0
  do_others_rescaling: true
  others_rescaling_iter_start: 30
  others_rescaling_iter_end: 50
  others_rescaling_factor: 2