run_name: ???
hydra:
  mode: ${hydra.mode}
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}___${run_name}
  sweep:
    dir: ./hydra_multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}___${run_name}
    subdir: ${hydra.job.num}

device: cuda:1
defaults:
  - guidance_cfg: exp20_ip
  - samples: empty_prompt

image_encoder_path: ./IP-Adapter/models/image_encoder
ip_ckpt: ./IP-Adapter/models/ip-adapter_sd15.bin

exp_configs:
  ip_scale: 0.75
  attn_guider_start: 25
  attn_guider_end: 50
  attn_guider_scale: 1.0
